name: Swiggy CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test -- --watchAll=false --passWithNoTests

    - name: Build project
      run: CI=false npm run build
    
    - name: Update Browserslist DB
      run: npx update-browserslist-db@latest
    

  code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npx eslint . --ext .js,.jsx,.ts,.tsx

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/swiggy_clone:${{ github.run_id }}

  updatek8s:
    runs-on: ubuntu-latest
    needs: docker

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}

    - name: Pull latest changes from remote
      run: |
        git fetch origin
        git pull origin master --rebase
      

    - name: Update tag in Kubernetes deployment manifest
      run: |
        sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/swiggy_clone:${{ github.run_id }}|" kubernetes/swiggy-deployment.yaml

    - name: Commit and push changes
      run: |
        git config --global user.email "sijomthomas05@gmail.com"
        git config --global user.name "sijomt"
        git add kubernetes/swiggy-deployment.yaml
        git commit -m "[CI]: Update swiggy-clone image tag"
        git push origin HEAD:master

